name: Deploy Frontend to Cloud Server

# 触发条件：当向 main 分支 push 代码时自动执行
on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 在 GitHub 虚拟机拉取源码
      - name: Checkout Code
        uses: actions/checkout@v3

      # 在 GitHub 虚拟机准备 Java 环境
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      # 在 GitHub 虚拟机里快速编译打包 Java (生成 target/*.jar)
      - name: Build Backend on GitHub Runner
        run: |
          cd backend
          mvn clean package -DskipTests

      - name: 远程 SSH 连接服务器并发布上线
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # 进入服务器上的项目目录
            cd /root/deadline-tracker/ 

            # 增加 Git 拉取重试机制，防止网络波动
            git fetch origin main || git fetch origin main || git fetch origin main
            git reset --hard origin/main


            # 重新构建并启动 
            docker-compose build --no-cache
            docker-compose up -d

            #清理废弃的临时构建镜像（防止占用云服务器磁盘）
            docker image prune -f
